language: python
python:
- '2.7'
- '3.5'
install: pip install .[tests]
script: python -m phabricator.tests.test_phabricator
deploy:
  provider: pypi
  user: disqus
  password:
    secure: AJ7zSLd6BgI4W8Kp3KEx5O40bUJA91PkgLTZb5MnCx4/8nUPlkk+LqvodaiiJQEGzpP8COPvRlzJ/swd8d0P38+Se6V83wA43MylimzrgngO6t3c/lXa/aMnrRzSpSfK5QznEMP2zcSU1ReD+2dNr7ATKajbGqTzrCFk/hQPMZ0=
  on:
    tags: true
