# Copyright (c) 2022 The Bitcoin developers

[package]
name = "chronik-util"
version = "0.1.0"
edition = "2021"
rust-version = "1.67.1"
license = "MIT"

[dependencies]
abc-rust-lint = { path = "../abc-rust-lint" }
chronik-bridge = { path = "../chronik-bridge" }
